### ISSUE TITLE
Currently having issues using the v0.1.3 release

### ISSUE THREAD

**Issue by The-Lord-of-Owls** [WilliamVenner/gluac-rs#1]
Version: v0.1.3 Release
CMD Usage: gluac_win32.exe -s -f test.lua
Binaries: Using the binaries from 32bit dedicated server
Notes: test.lua is located alongside where the exe is at currently

ERROR:
←LJ☺☻thread 'main' panicked at 'Failed to write to stdout: Error { kind: InvalidData, message: "Windows stdio in console mode does not support writing non-UTF-8 byte sequences" }', src\bin\gluac.rs:54:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by WilliamVenner** [comment]
Hi, in v0.1.4 you can now use the `-o output.luac` flag to output to a file rather than the console.
